sudo: required
env:
        REPO_NAME=alpine-s6-base
services:
        - docker
language: bash
script:
        # build amd64
        #- docker build --build-arg=amd64 -t $DOCKER_USER/$REPO_NAME:amd64-latest .
        # push image
        #- . docker_push amd64
        
        # build arm32v7
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --build-arg ARCH=arm -t $DOCKER_USER/$REPO_NAME:armhf-latest .
        #push image
        - . docker_push armhf
