sudo: required
env:
        REPO_NAME=alpine-s6-base
services:
        - docker
language: bash
script:
        - docker build -t $DOCKER_USER/$REPO_NAME .
        # push image
        - . docker_push  
        # build arm32v7 image
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker run --rm --privileged arm32v7/debian
        - docker build -t $DOCKER_USER/$REPO_NAME .
        - . docker_push
